### ISSUE TITLE
Bumped into ResourceExhaustedError while testing fix_temporary_defaults

### ISSUE THREAD

**Issue by plt109** [FlamTeam/flamedisx#111]
While reviewing PR#101, I tested `fix_temporary_defaults` by fitting some(~3k) real events (crunching on a  GPU) and I bumped into a ResourceExhaustedError error. The same fit with the full dataset (~3k events) converges on `master`. 

The same fit converges without memory issues with 10, 100, 1000 events on `fix_temporary_defaults`, but fails with the ResourceExhaustedError with 1500 events on `fix_temporary_defaults`. It also failed when I reverted back to 1000 events, but converges with 500 events, and converges with 1000 events after that.

I have also checked that there are no other processes competing for the resources.

Is it possible for `deepcopy` to introduce memory leaks? (I guess memory leaks do occur in Python...)

The codes I used are(largely, not sure how much details to provide to make it helpful):
```
class mySource(fd.SR1ERSource):
    energies = tf.cast(tf.linspace(0., 13., 1000),
                       dtype=fd.float_type())

ll = fd.LogLikelihood(sources=dict(er=mySource, ac=myAC),
                                batch_size = 100,
                                free_rates = 'er',
                                ...
                                elife = nuisance_range['elife'],
                                progress=False,
                             )
bf = ll.bestfit(guess=ll.guess(), optimizer='scipy')
```

The error I bumped into is:
```
---------------------------------------------------------------------------
ResourceExhaustedError                    Traceback (most recent call last)
<ipython-input-40-d118ddff446a> in <module>
     27 
     28     tt_start = dt.datetime.now()
---> 29     whack2_result = whack2.bestfit(guess=whack2_guess, optimizer='scipy')
     30     tt_stop = dt.datetime.now()
     31     print('Time taken run %i: %s' % (irun, tt_stop-tt_start))

~/flamedisx/flamedisx/likelihood.py in bestfit(self, guess, fix, bounds, optimizer, get_lowlevel_result, get_history, use_hessian, return_errors, nan_val, optimizer_kwargs, allow_failure)
    524         # Check the likelihood has a finite value and gradient before starting
    525         val, grad, hess = self.log_likelihood(**guess,
--> 526                                               second_order=use_hessian)
    527         if not np.isfinite(val):
    528             raise ValueError("The likelihood is - infinity at your guess, "

~/flamedisx/flamedisx/likelihood.py in log_likelihood(self, second_order, omit_grads, **kwargs)
    329                     omit_grads=omit_grads,
    330                     second_order=second_order,
--> 331                     **params)
    332                 ll += results[0].numpy().astype(np.float64)
    333 

~/.conda/envs/fd-test/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    778       else:
    779         compiler = "nonXla"
--> 780         result = self._call(*args, **kwds)
    781 
    782       new_tracing_count = self._get_tracing_count()

~/.conda/envs/fd-test/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    844               *args, **kwds)
    845       # If we did not create any variables the trace we have is good enough.
--> 846       return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
    847 
    848     def fn_with_cond(*inner_args, **inner_kwds):

~/.conda/envs/fd-test/lib/python3.6/site-packages/tensorflow/python/eager/function.py in _filtered_call(self, args, kwargs, cancellation_manager)
   1846                            resource_variable_ops.BaseResourceVariable))],
   1847         captured_inputs=self.captured_inputs,
-> 1848         cancellation_manager=cancellation_manager)
   1849 
   1850   def _call_flat(self, args, captured_inputs, cancellation_manager=None):

~/.conda/envs/fd-test/lib/python3.6/site-packages/tensorflow/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1922       # No tape is watching; skip to running the function.
   1923       return self._build_call_outputs(self._inference_function.call(
-> 1924           ctx, args, cancellation_manager=cancellation_manager))
   1925     forward_backward = self._select_forward_and_backward_functions(
   1926         args,

~/.conda/envs/fd-test/lib/python3.6/site-packages/tensorflow/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    548               inputs=args,
    549               attrs=attrs,
--> 550               ctx=ctx)
    551         else:
    552           outputs = execute.execute_with_cancellation(

~/.conda/envs/fd-test/lib/python3.6/site-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted:  OOM when allocating tensor with shape[100,105,455] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node while/body/_12/while/gradients/gradients_1/Lgamma_7_grad/mul_grad/Mul_1}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[while/LoopCond/_1637/_204]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted:  OOM when allocating tensor with shape[100,105,455] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node while/body/_12/while/gradients/gradients_1/Lgamma_7_grad/mul_grad/Mul_1}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored. [Op:__inference__log_likelihood_36332]

Function call stack:
_log_likelihood -> _log_likelihood
```

**Comment by plt109** [comment]
Update: Managed to fit without memory issues after decreasing the batch size from 100 to 50 and the median running time increased from ~5.7 mins to ~13.7 mins.

**Comment by JelleAalbers** [comment]
Thanks for reporting Pueh. It sounds like the GPU memory requirements have increased, forcing you to use a smaller batch size. However this

> It also failed when I reverted back to 1000 events, but converges with 500 events, and converges with 1000 events after that.

is strange. 

I also don't understand how a change in `_set_temporarily` could trigger this. That function is only used in `simulate` and `annotate_data`, and neither of these is called when computing a likelihood. Perhaps it's the calls to simulate/annotate earlier on (e.g. when constructing a likelihood) that reserve some memory that is not cleared, so you have less available when you start fitting?

I changed #110 to use `copy` instead of `deepcopy` now, maybe this helps.

Finally it's odd that tensorflow asks you to look into `report_tensor_allocations_upon_oom`, while this option seems to be absent in tensorflow 2. Maybe it's still accessible via the compatibility v1 API? Could be worth looking into to further diagnose this issue.

**Comment by JelleAalbers** [comment]
This error is indeed the result when using a too large batch size for the GPU: you will and should see this message if you use too large batch sizes on any branch (before or after #110).

A simple example to reproduce is:

```python
import flamedisx as fd
df = fd.ERSource().simulate(3_000)
ll = fd.LogLikelihood(sources=dict(er=fd.ERSource), 
                      data=df, 
                      batch_size=1_500)
ll()
```

The exact maximum batch size depends on your GPU and maybe your application (I would guess a fit needs a bit more memory, especially if using the Hessian). The above is enough to trigger ResourceExhaustedError on a Tesla T4 on Colab; it can handle `batch_size=1_000`. 

  * With `batch_size = 500`, the above code uses 8960 MiB on both master and #110, based on running `nvidia-smi` immediately afterwards (as noted in #106, tensorflow is not exactly keen on clearing memory).
  * If I add `elife=(200e3, 800e3, 2),` to the likelihood setup the memory usage jumps to 14376 MiB (1.6x) on #110, but actually _decreases_ slightly to 8576 MiB on master (0.95x). 
  * Adding more parameters, e.g. `er_pel_a=(14., 17., 2)`, does not change the memory required.

So I can confirm your observation: after `fix_temporary_defaults`, our GPU memory footprint is increased by ~60%. Now let's try to figure out why...

**Comment by JelleAalbers** [comment]
Turns out the cause is much more mundane than I feared: It's not the bugfix's fault, but the bug. The bug caused a wrong -- too high -- electron lifetime to be used for bounds estimation. Suppose you do this:

```python
# Simulate data (or load from file, does not matter)
df = fd.ERSource().simulate(3000)

ll = fd.LogLikelihood(sources=dict(er=fd.ERSource), 
                      elife=(200e3, 800e3, 2),
                      batch_size=500)
```
On master, due to the bug, the source's default elife has now incorrectly been changed to 800e3 us. If you `set_data(df)` now (or equivalently pass `data=df` when making the likelihood) the data will be annotated assuming the elife is 800e3 us.

At high elifes / larger efficiencies, flamedisx's internal tensors are smaller and consume less memory.

To prove this is what is happening, you can follow up the code above with this on master:
```python
# This resets the default elife to 452e3 us
# as a side-effect of simulate.
ll.simulate()  

# Bounds estimation now uses the correct 452e3 us as elife
ll.set_data(df)
ll()
```
This will show the 60% increased memory consumption *on master*. We didn't apply the bugfix, but simply worked around the bug by resetting the defaults (with a `simulate` call).

So there is no problem with the bugfix: the increased memory usage is simply what is required to correctly compute the likelihood. 

(In fact, if you had `1/elife` as a parameter, or if flamedisx did the mu simulation for the high elife before the one for the low elife, you would see the opposite effect: master would consume more memory and the fixed branch would take less.)

**Comment by robertsjames** [comment]
Of course, just a friendly reminder that once I put my NEST structure updates into 'original' FLAMEDISX, tensor sizes growing won't be an issue anymore; that'll be handled by the variable stepping. For those of you who don't know what I'm talking about, all will be revealed in our meeting on Friday :P
